-- Dicionário de afixos dos valores dos números

config.numAffixes = {
	{key = "K", name = "Thousand"}, -- 10e3
	{key = "M", name = "Million"}, -- 10e6
	{key = "B", name = "Billion"}, -- 10e9
	{key = "T", name = "Trillion"}, -- 10e12
	{key = "Qa", name = "Quadrillion"}, -- 10e15
	{key = "Qi", name = "Quintillion"}, -- 10e18
	{key = "Sx", name = "Sextillion"}, -- 10e21
	{key = "Sp", name = "Septillion"}, -- 10e24
	{key = "Oc", name = "Octillion"}, -- 10e27
	{key = "No", name = "Nonillion"}, -- 10e30
	{key = "Dc", name = "Decillion"}, -- 10e33
	{key = "Un", name = "Undecillion"}, -- 10e36
	{key = "Du", name = "Duodecillion"}, -- 10e39
	{key = "Tr", name = "Tredecillion"}, -- 10e42
	{key = "Qad", name = "Quattuordecillion"}, -- 10e45
	{key = "Qid", name = "Quinquadecillion"}, -- 10e48
	{key = "Sd", name = "Sedecillion"}, -- 10e51
	{key = "Spd", name = "Septendecillion"}, -- 10e54
	{key = "Ocd", name = "Octodecillion"}, -- 10e57
	{key = "Nvd", name = "Novendecillion"}, -- 10e60
	{key = "V", name = "Vigintillion"}, -- 10e63
	{key = "Unv", name = "Unvigintillion"}, -- 10e66
	{key = "Duv", name = "Duovigintillion"}, -- 10e69
	{key = "Trv", name = "Tresvigintillion"}, -- 10e72
	{key = "Qav", name = "Quattuorvigintillion"}, -- 10e75
	{key = "Qiv", name = "Quinquavigintillion"}, -- 10e78
	{key = "Sev", name = "Sesvigintillion"}, -- 10e81
	{key = "Spv", name = "Septemvigintillion"}, -- 10e84
	{key = "Ocv", name = "Octovigintillion"}, -- 10e87
	{key = "Nvv", name = "Novemvigintillion"}, -- 10e90
	{key = "Trt", name = "Trigintillion"}, -- 10e93
	{key = "Unt", name = "Untrigintillion"}, -- 10e96
	{key = "Dut", name = "Duotrigintillion"}, -- 10e99
	{key = "Trt", name = "Trestrigintillion"}, -- 10e102
	{key = "Qat", name = "Quattuortrigintillion"}, -- 10e105
	{key = "Qit", name = "Quinquatrigintillion"}, -- 10e108
	{key = "Set", name = "Sestrigintillion"}, -- 10e111
	{key = "Spt", name = "Septentrigintillion"}, -- 10e114
	{key = "Oct", name = "Octotrintillion"}, -- 10e117
	{key = "Nvt", name = "Noventrigintillion"}, -- 10e120
	{key = "Qag", name = "Quadragintillion"}, -- 10e123
}
